/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Ankit' at '10/4/16 11:11 AM' with Gradle 3.1
 *
 * @author Ankit, @date 10/4/16 11:11 AM
 */
public class Library {

    public  static  void testFUnc(){
        System.out.println("tefragj");
    }

    public boolean someLibraryMethod() {
        return true;
    }

    public static void  main(String str[]){
        testFUnc();
    }
}

